---
- hosts: spark-master
  vars:
    spark_home: "{{ spark_dir }}{{ spark_version }}"
    spark_master_host_string: "spark://{{ spark_master_host }}:7077"

  tasks:
    - git:
        repo: "{{ git_repo }}"
        dest: "{{ git_dest }}"

    - name: "Python: {{ spark_job_name }}"
      command: sh {{ spark_home }}/bin/spark-submit --master {{ spark_master_host_string }} {{ git_dest }}/{{ exec_path }} {{ spark_job_args }}
      when: class_name == ""

    - name: "Scala: {{ spark_job_name }}"
      command: sh {{ spark_home }}/bin/spark-submit --master {{ spark_master_host_string }} --class {{ class_name }} {{ git_dest }}/{{ exec_path }} {{ spark_job_args }}
      when: class_name != ""
