- name: Start Spark Master
  template:
    src: spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service
    mode: 755
    force: yes

- name: Start Spark History Server
  template:
    src: sparkhs.service.j2
    dest: /etc/systemd/system/sparkhs.service
    mode: 755
    force: yes

- name: Force systemd to reread configs
  systemd: 
    daemon_reload: yes

- name: Start Spark Master
  systemd: 
    name: spark-master
    state: restarted 
    enabled: yes

- name: Start Spark History Server
  systemd: 
    name: sparkhs
    state: restarted 
    enabled: yes