- name: "Create group spark"
  group:
    name: "spark"
    state: present

- name: "Add user spark"
  user:
    name: "spark"
    group: "spark"

- name: Install Java and other packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - "{{ java.yum_package }}"
    - nc
    - git
    - python3-pip

- name: Pip install virtualenv
  pip:
    name: virtualenv
    executable: pip3

- name: Create virtualenv
  shell: /usr/local/bin/virtualenv /home/spark/sparkenv
  become: true
  become_user: spark

- name: Pip install in virtualenv
  shell: /home/spark/sparkenv/bin/pip install numpy pandas
  become: yes
  become_user: spark