- name: Install Java and other packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - "{{ java.yum_package }}"
    - nc
    - git

- name: "Check if anaconda install script exists"
  stat: path=/tmp/Anaconda3-2019.07-Linux-x86_64.sh
  register: anaconda_sh_exists

- name: Download Anaconda
  get_url:
    url: https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
    dest: /tmp
    mode: '0755'
  when: not anaconda_sh_exists.stat.exists

- name: Install Anaconda
  command: /tmp/Anaconda3-2019.07-Linux-x86_64.sh -b -u -p /usr/anaconda3