---
- hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: true
  roles:
    - prereq
    - spark

- hosts: spark_master
  any_errors_fatal: true
  gather_facts: no
  become: true
  roles:
    - start_spark_master

- hosts: spark_worker
  any_errors_fatal: true
  gather_facts: no
  become: true
  roles:
    - start_spark_workers

- hosts: spark_master
  any_errors_fatal: true
  gather_facts: no
  become: true
  roles:
    - execute_on_spark