---
- hosts: spark-master
  vars:
    spark_home: "{{ spark_dir }}{{ spark_version }}"
  tasks:

    - name: Create file spark-defaults.conf
      command: sh -c "echo {{ item }} >> {{ spark_home }}/conf/spark-defaults.conf"
      with_items:
        - spark.history.fs.logDirectory file:///var/log/spark/apps
        - spark.eventLog.dir file:///var/log/spark/apps
        - spark.eventLog.enabled true
        - "spark.master spark://{{ spark_master_host }}:7077"
      become: yes
      become_user: spark

    - name: Create Spark Log directory
      file:
        path: /var/log/spark/apps
        owner: spark
        group: spark
        state: directory
        mode: 0777
        recurse: yes
      become: yes

    - name: Start Spark History Server - First Attempt
      command: sh {{ spark_home }}/sbin/start-history-server.sh
      become: yes
      become_user: spark

    - name: Start Spark History Server - Second Attempt
      command: sh {{ spark_home }}/sbin/start-history-server.sh
      become: yes
      become_user: spark
      ignore_errors: yes

    - name: Start Spark Master
      command: sh {{ spark_home }}/sbin/start-master.sh
      become: yes
      become_user: spark
