---
- hosts: spark-*
  vars:
    spark_home: "{{ spark_dir }}{{ spark_version }}"

  tasks:
    - name: Create spark-env.sh
      command: sh -c "echo {{ item }} >> {{ spark_home }}/conf/spark-env.sh"
      with_items:
        - "SPARK_MASTER_HOST={{ spark_master_host }}"
        -  "PYSPARK_PYTHON=/usr/anaconda/bin/python"
      become: yes
      become_user: spark
