---
- hosts: spark-slave
  vars:
    spark_home:  "/usr/spark/spark-2.4.0-bin-hadoop2.7"
  tasks:

    - name: Start Spark History Server
      command: sh {{ spark_home }}/sbin/start-slave.sh spark://{{ spark_master_host }}:7077
      become: yes
      become_user: spark
